#include <MDR_1923KX028_M2_Defs.h>

const uint32_t MDR_KX028_AxiAddrEMAC[KX028_EMAC_NUMS] =
{
    AXI_EMAC1_BASE_ADDR,
    AXI_EMAC2_BASE_ADDR,
    AXI_EMAC3_BASE_ADDR,
    AXI_EMAC4_BASE_ADDR,
    AXI_EMAC5_BASE_ADDR,
    AXI_EMAC6_BASE_ADDR,
    AXI_EMAC7_BASE_ADDR,
    AXI_EMAC8_BASE_ADDR,
    AXI_EMAC9_BASE_ADDR,
    AXI_EMAC10_BASE_ADDR,
    AXI_EMAC11_BASE_ADDR,
    AXI_EMAC12_BASE_ADDR,
    AXI_EMAC13_BASE_ADDR,
    AXI_EMAC14_BASE_ADDR,
    AXI_EMAC15_BASE_ADDR,
    AXI_EMAC16_BASE_ADDR
};

const uint32_t MDR_KX028_AxiAddrEGPI[KX028_EMAC_NUMS] =
{
    AXI_EGPI1_BASE_ADDR,
    AXI_EGPI2_BASE_ADDR,
    AXI_EGPI3_BASE_ADDR,
    AXI_EGPI4_BASE_ADDR,
    AXI_EGPI5_BASE_ADDR,
    AXI_EGPI6_BASE_ADDR,
    AXI_EGPI7_BASE_ADDR,
    AXI_EGPI8_BASE_ADDR,
    AXI_EGPI9_BASE_ADDR,
    AXI_EGPI10_BASE_ADDR,
    AXI_EGPI11_BASE_ADDR,
    AXI_EGPI12_BASE_ADDR,
    AXI_EGPI13_BASE_ADDR,
    AXI_EGPI14_BASE_ADDR,
    AXI_EGPI15_BASE_ADDR,
    AXI_EGPI16_BASE_ADDR
};

const uint32_t MDR_KX028_AxiAddrETGPI[KX028_EMAC_NUMS] =
{
    AXI_ETGPI1_BASE_ADDR,
    AXI_ETGPI2_BASE_ADDR,
    AXI_ETGPI3_BASE_ADDR,
    AXI_ETGPI4_BASE_ADDR,
    AXI_ETGPI5_BASE_ADDR,
    AXI_ETGPI6_BASE_ADDR,
    AXI_ETGPI7_BASE_ADDR,
    AXI_ETGPI8_BASE_ADDR,
    AXI_ETGPI9_BASE_ADDR,
    AXI_ETGPI10_BASE_ADDR,
    AXI_ETGPI11_BASE_ADDR,
    AXI_ETGPI12_BASE_ADDR,
    AXI_ETGPI13_BASE_ADDR,
    AXI_ETGPI14_BASE_ADDR,
    AXI_ETGPI15_BASE_ADDR,
    AXI_ETGPI16_BASE_ADDR
};


const uint32_t KX028_PortOffsStruct1[AXI_CLASS_PORT_COUNT] = {
  AXI_CLASS_PORT0_STRUC1,
  AXI_CLASS_PORT1_STRUC1,
  AXI_CLASS_PORT2_STRUC1,
  AXI_CLASS_PORT3_STRUC1,
  AXI_CLASS_PORT4_STRUC1,
  AXI_CLASS_PORT5_STRUC1,
  AXI_CLASS_PORT6_STRUC1,
  AXI_CLASS_PORT7_STRUC1,
  AXI_CLASS_PORT8_STRUC1,
  AXI_CLASS_PORT9_STRUC1,
  AXI_CLASS_PORT10_STRUC1,
  AXI_CLASS_PORT11_STRUC1,
  AXI_CLASS_PORT12_STRUC1,
  AXI_CLASS_PORT13_STRUC1,
  AXI_CLASS_PORT14_STRUC1,
  AXI_CLASS_PORT15_STRUC1,
  AXI_CLASS_PORT16_STRUC1,
};

const uint32_t KX028_PortOffsStruct2[AXI_CLASS_PORT_COUNT] = {
  AXI_CLASS_PORT0_STRUC2,
  AXI_CLASS_PORT1_STRUC2,
  AXI_CLASS_PORT2_STRUC2,
  AXI_CLASS_PORT3_STRUC2,
  AXI_CLASS_PORT4_STRUC2,
  AXI_CLASS_PORT5_STRUC2,
  AXI_CLASS_PORT6_STRUC2,
  AXI_CLASS_PORT7_STRUC2,
  AXI_CLASS_PORT8_STRUC2,
  AXI_CLASS_PORT9_STRUC2,
  AXI_CLASS_PORT10_STRUC2,
  AXI_CLASS_PORT11_STRUC2,
  AXI_CLASS_PORT12_STRUC2,
  AXI_CLASS_PORT13_STRUC2,
  AXI_CLASS_PORT14_STRUC2,
  AXI_CLASS_PORT15_STRUC2,
  AXI_CLASS_PORT16_STRUC2,
};



